# Image Storage Processing

In [1]:
# import libraries for data processing
import numpy as np
import pandas as pd

# import libraries for file manipulation + system management
import os
import requests
import shutil
from urllib.parse import urlparse

# import dependency from image processing toolkit
from image_processing_tools import distribute_images
from image_processing_tools import remove_images
from image_processing_tools import det_folder_size

### ISP-Approach

+ Loading Images
+ Download images into source images (IF NEEDED)
+ Distributing stored images from source path to new destination path
+ Image Reorganisation based on labels

## Loading Images

In [2]:
# load dataset 
image_ds_file = "image_dataset.csv"
image_df = pd.read_csv(image_ds_file, index_col=0)
image_df.head()

,Image_file,Labels,Model,Company
0,image_000.jpg,Samsung SM-A156B Galaxy A15 Dual SIM 5G 4GB RA...,SM-A156B Galaxy,Samsung
1,image_001.jpg,Samsung SM-A556B Galaxy A55 5G Dual SIM 8GB 12...,SM-A556B Galaxy,Samsung
2,image_002.jpg,Motorola Moto G54 256GB Blue 5G Android Smartp...,Moto G54,Motorola
3,image_003.jpg,Xiaomi 14 Ultra 5G 16GB/512GB White (White) Du...,14 Ultra,Xiaomi
4,image_004.jpg,Samsung Galaxy S20 FE 5G 6GB/128GB Purple (Lav...,Galaxy S20,Samsung

In [3]:
image_df["Company"].value_counts()

Company
Samsung      345
Xiaomi       167
Apple        105
Nokia        103
Motorola      30
OnePlus       26
Redmi         13
Poco          10
Microsoft      1
Name: count, dtype: int64

## Distribution of stored images

In [4]:
# data splitting: create constants for number of images in train, test and validation folders 
train_size = 800
test_size = 160
validation_size = 40

In [5]:
# create list of folders
path = "D:\\Machine_Learning\\Portfolio_Project_Machine_Learning\\Mobile_Phone_Recognition\\datasets"
dataset_paths = os.listdir(path)
dataset_paths.remove("dataset_structure")
print(f"Dataset Paths: {dataset_paths}")

# create constants: source folder and destination folder (train, test and validation folder) 
source_path = os.path.join(path, dataset_paths[1])
destination_path = os.path.join(path, dataset_paths[0])
  
for folder_name, path_idx in zip(["Destination Folder", "Source Folder"], dataset_paths):
  ds_path = os.path.join(path, path_idx)
  print(f"{folder_name} Folder: {ds_path}")

Dataset Paths: ['distributed_images', 'source_images', 'source_images_v1', 'source_images_v2']
Destination Folder Folder: D:\Machine_Learning\Portfolio_Project_Machine_Learning\Mobile_Phone_Recognition\datasets\distributed_images
Source Folder Folder: D:\Machine_Learning\Portfolio_Project_Machine_Learning\Mobile_Phone_Recognition\datasets\source_images

In [6]:
# update 1: train and test sizes
train_size1 = 0.8
test_size1 = 0.2

# update 2: train and test images
train_size2 = 0.7
test_size2 = 0.3

In [7]:
# remove images from current folder 
remove_images(current_folder=destination_path)

In [8]:
# distribute images in training, testing and validation folder  
distribute_images(source_folder=source_path, 
                  destination_folder=destination_path, 
                  df_file=image_ds_file,
                  update_train_size=train_size2,
                  update_test_size=test_size2)

Moved image_000.jpg to train\Samsung
Moved image_000.jpg to train\Samsung
Moved image_001.jpg to train\Samsung
Moved image_003.jpg to train\Xiaomi
Moved image_002.jpg to train\Motorola
Moved image_001.jpg to train\Samsung
Moved image_004.jpg to train\Samsung
Moved image_004.jpg to train\Samsung
Moved image_006.jpg to train\Samsung
Moved image_007.jpg to train\Samsung
Moved image_005.jpg to train\Samsung
Moved image_003.jpg to train\Xiaomi
Moved image_006.jpg to train\Samsung
Moved image_000.jpg to train\Samsung
Moved image_009.jpg to train\Samsung
Moved image_002.jpg to train\Motorola
Moved image_014.jpg to train\Samsung
Moved image_013.jpg to train\Xiaomi
Moved image_008.jpg to train\Samsung
Moved image_016.jpg to train\Samsung
Moved image_007.jpg to train\Samsung
Moved image_010.jpg to train\Samsung
Moved image_009.jpg to train\Samsung
Moved image_021.jpg to train\Xiaomi
Moved image_015.jpg to train\Samsung
Moved image_012.jpg to train\Xiaomi
Moved image_005.jpg to train\Samsung
Moved image_009.jpg to train\Samsung
Moved image_014.jpg to train\Samsung
Moved image_027.jpg to train\Samsung
Moved image_023.jpg to train\Samsung
Moved image_007.jpg to train\Samsung
Moved image_008.jpg to train\Samsung
Moved image_001.jpg to train\Samsung
Moved image_004.jpg to train\Samsung
Moved image_019.jpg to train\Samsung
Moved image_032.jpg to train\Motorola
Moved image_013.jpg to train\Xiaomi
Moved image_013.jpg to train\Xiaomi
Moved image_013.jpg to train\Xiaomi
Moved image_010.jpg to train\Samsung
Moved image_008.jpg to train\Samsung
Moved image_031.jpg to train\Motorola
Moved image_008.jpg to train\Samsung
Moved image_002.jpg to train\Motorola
Moved image_045.jpg to train\Motorola
Moved image_041.jpg to train\Samsung
Moved image_029.jpg to train\Samsung
Moved image_006.jpg to train\Samsung
Moved image_026.jpg to train\Xiaomi
Moved image_041.jpg to train\Samsung
Moved image_002.jpg to train\Motorola
Moved image_050.jpg to train\Nokia
Moved image_041.jpg to train\Samsung
Moved image_014.jpg to train\Samsung
Moved image_034.jpg to train\Xiaomi
Moved image_029.jpg to train\Samsung
Moved image_048.jpg to train\Xiaomi
Moved image_019.jpg to train\Samsung
Moved image_034.jpg to train\Xiaomi
Moved image_059.jpg to train\Samsung
Moved image_020.jpg to train\Samsung
Moved image_020.jpg to train\Samsung
Moved image_046.jpg to train\Samsung
Moved image_042.jpg to train\Xiaomi
Moved image_028.jpg to train\Motorola
Moved image_033.jpg to train\Samsung
Moved image_037.jpg to train\Samsung
Moved image_048.jpg to train\Xiaomi
Moved image_022.jpg to train\Samsung
Moved image_007.jpg to train\Samsung
Moved image_000.jpg to train\Samsung
Moved image_013.jpg to train\Xiaomi
Moved image_039.jpg to train\Samsung
Moved image_044.jpg to train\Nokia
Moved image_072.jpg to train\Redmi
Moved image_009.jpg to train\Samsung
Moved image_023.jpg to train\Samsung
Moved image_077.jpg to train\Redmi
Moved image_016.jpg to train\Samsung
Moved image_052.jpg to train\Samsung
Moved image_030.jpg to train\Samsung
Moved image_027.jpg to train\Samsung
Moved image_032.jpg to train\Motorola
Moved image_016.jpg to train\Samsung
Moved image_027.jpg to train\Samsung
Moved image_000.jpg to train\Samsung
Moved image_017.jpg to train\Samsung
Moved image_068.jpg to train\Samsung
Moved image_005.jpg to train\Samsung
Moved image_081.jpg to train\Xiaomi
Moved image_018.jpg to train\Nokia
Moved image_005.jpg to train\Samsung
Moved image_003.jpg to train\Xiaomi
Moved image_093.jpg to train\Xiaomi
Moved image_020.jpg to train\Samsung
Moved image_006.jpg to train\Samsung
Moved image_012.jpg to train\Xiaomi
Moved image_013.jpg to train\Xiaomi
Moved image_031.jpg to train\Motorola
Moved image_017.jpg to train\Samsung
Moved image_100.jpg to train\Samsung
Moved image_021.jpg to train\Xiaomi
Moved image_047.jpg to train\Motorola
Moved image_031.jpg to train\Motorola
Moved image_018.jpg to train\Nokia
Moved image_012.jpg to train\Xiaomi
Moved image_023.jpg to train\Samsung
Moved image_058.jpg to train\Samsung
Moved image_011.jpg to train\Samsung
Moved image_022.jpg to train\Samsung
Moved image_056.jpg to train\Motorola
Moved image_079.jpg to train\Xiaomi
Moved image_045.jpg to train\Motorola
Moved image_105.jpg to train\Samsung
Moved image_060.jpg to train\Samsung
Moved image_106.jpg to train\Samsung
Moved image_000.jpg to train\Samsung
Moved image_079.jpg to train\Xiaomi
Moved image_114.jpg to train\Samsung
Moved image_033.jpg to train\Samsung
Moved image_029.jpg to train\Samsung
Moved image_070.jpg to train\Xiaomi
Moved image_077.jpg to train\Redmi
Moved image_010.jpg to train\Samsung
Moved image_011.jpg to train\Samsung
Moved image_061.jpg to train\Nokia
Moved image_015.jpg to train\Samsung
Moved image_114.jpg to train\Samsung
Moved image_009.jpg to train\Samsung
Moved image_003.jpg to train\Xiaomi
Moved image_055.jpg to train\Samsung
Moved image_038.jpg to train\Xiaomi
Moved image_122.jpg to train\Apple
Moved image_012.jpg to train\Xiaomi
Moved image_131.jpg to train\Samsung
Moved image_036.jpg to train\Nokia
Moved image_091.jpg to train\Xiaomi
Moved image_135.jpg to train\Samsung
Moved image_110.jpg to train\Samsung
Moved image_032.jpg to train\Motorola
Moved image_050.jpg to train\Nokia
Moved image_106.jpg to train\Samsung
Moved image_033.jpg to train\Samsung
Moved image_115.jpg to train\Samsung
Moved image_103.jpg to train\Samsung
Moved image_026.jpg to train\Xiaomi
Moved image_021.jpg to train\Xiaomi
Moved image_135.jpg to train\Samsung
Moved image_070.jpg to train\Xiaomi
Moved image_044.jpg to train\Nokia
Moved image_108.jpg to train\Xiaomi
Moved image_106.jpg to train\Samsung
Moved image_047.jpg to train\Motorola
Moved image_034.jpg to train\Xiaomi
Moved image_103.jpg to train\Samsung
Moved image_143.jpg to train\Xiaomi
Moved image_157.jpg to train\Samsung
Moved image_047.jpg to train\Motorola
Moved image_134.jpg to train\Samsung
Moved image_155.jpg to train\Samsung
Moved image_014.jpg to train\Samsung
Moved image_006.jpg to train\Samsung
Moved image_091.jpg to train\Xiaomi
Moved image_052.jpg to train\Samsung
Moved image_104.jpg to train\Nokia
Moved image_012.jpg to train\Xiaomi
Moved image_083.jpg to train\Xiaomi
Moved image_044.jpg to train\Nokia
Moved image_044.jpg to train\Nokia
Moved image_089.jpg to train\Samsung
Moved image_132.jpg to train\Xiaomi
Moved image_080.jpg to train\Xiaomi
Moved image_167.jpg to train\Samsung
Moved image_138.jpg to train\Samsung
Moved image_045.jpg to train\Motorola
Moved image_009.jpg to train\Samsung
Moved image_141.jpg to train\Samsung
Moved image_004.jpg to train\Samsung
Moved image_114.jpg to train\Samsung
Moved image_116.jpg to train\Samsung
Moved image_063.jpg to train\Xiaomi
Moved image_176.jpg to train\Samsung
Moved image_114.jpg to train\Samsung
Moved image_085.jpg to train\Xiaomi
Moved image_046.jpg to train\Samsung
Moved image_180.jpg to train\Samsung
Moved image_054.jpg to train\Samsung
Moved image_048.jpg to train\Xiaomi
Moved image_148.jpg to train\Samsung
Moved image_035.jpg to train\Samsung
Moved image_083.jpg to train\Xiaomi
Moved image_065.jpg to train\Xiaomi
Moved image_023.jpg to train\Samsung
Moved image_159.jpg to train\Samsung
Moved image_156.jpg to train\Samsung
Moved image_133.jpg to train\Motorola
Moved image_001.jpg to train\Samsung
Moved image_122.jpg to train\Apple
Moved image_071.jpg to train\Xiaomi
Moved image_052.jpg to train\Samsung
Moved image_055.jpg to train\Samsung
Moved image_008.jpg to train\Samsung
Moved image_155.jpg to train\Samsung
Moved image_198.jpg to train\Xiaomi
Moved image_041.jpg to train\Samsung
Moved image_177.jpg to train\Samsung
Moved image_194.jpg to train\Samsung
Moved image_112.jpg to train\Samsung
Moved image_024.jpg to train\Samsung
Moved image_066.jpg to train\Xiaomi
Moved image_008.jpg to train\Samsung
Moved image_160.jpg to train\Samsung
Moved image_199.jpg to train\Nokia
Moved image_041.jpg to train\Samsung
Moved image_008.jpg to train\Samsung
Moved image_092.jpg to train\Redmi
Moved image_198.jpg to train\Xiaomi
Moved image_037.jpg to train\Samsung
Moved image_197.jpg to train\Samsung
Moved image_134.jpg to train\Samsung
Moved image_068.jpg to train\Samsung
Moved image_085.jpg to train\Xiaomi
Moved image_201.jpg to train\Xiaomi
Moved image_065.jpg to train\Xiaomi
Moved image_199.jpg to train\Nokia
Moved image_069.jpg to train\Nokia
Moved image_074.jpg to train\Xiaomi
Moved image_089.jpg to train\Samsung
Moved image_213.jpg to train\Nokia
Moved image_085.jpg to train\Xiaomi
Moved image_101.jpg to train\Samsung
Moved image_175.jpg to train\Samsung
Moved image_075.jpg to train\Xiaomi
Moved image_056.jpg to train\Motorola
Moved image_198.jpg to train\Xiaomi
Moved image_044.jpg to train\Nokia
Moved image_106.jpg to train\Samsung
Moved image_133.jpg to train\Motorola
Moved image_169.jpg to train\Samsung
Moved image_053.jpg to train\Xiaomi
Moved image_050.jpg to train\Nokia
Moved image_031.jpg to train\Motorola
Moved image_014.jpg to train\Samsung
Moved image_151.jpg to train\Samsung
Moved image_017.jpg to train\Samsung
Moved image_008.jpg to train\Samsung
Moved image_019.jpg to train\Samsung
Moved image_043.jpg to train\Samsung
Moved image_092.jpg to train\Redmi
Moved image_031.jpg to train\Motorola
Moved image_109.jpg to train\Samsung
Moved image_160.jpg to train\Samsung
Moved image_102.jpg to train\Samsung
Moved image_189.jpg to train\Samsung
Moved image_235.jpg to train\Nokia
Moved image_214.jpg to train\Samsung
Moved image_011.jpg to train\Samsung
Moved image_106.jpg to train\Samsung
Moved image_033.jpg to train\Samsung
Moved image_046.jpg to train\Samsung
Moved image_212.jpg to train\Motorola
Moved image_127.jpg to train\Apple
Moved image_252.jpg to train\Nokia
Moved image_021.jpg to train\Xiaomi
Moved image_223.jpg to train\Samsung
Moved image_082.jpg to train\Xiaomi
Moved image_204.jpg to train\Samsung
Moved image_237.jpg to train\Samsung
Moved image_249.jpg to train\Samsung
Moved image_039.jpg to train\Samsung
Moved image_117.jpg to train\Samsung
Moved image_207.jpg to train\Samsung
Moved image_051.jpg to train\Nokia
Moved image_128.jpg to train\Samsung
Moved image_006.jpg to train\Samsung
Moved image_121.jpg to train\Apple
Moved image_245.jpg to train\Samsung
Moved image_184.jpg to train\Samsung
Moved image_046.jpg to train\Samsung
Moved image_147.jpg to train\Apple
Moved image_083.jpg to train\Xiaomi
Moved image_272.jpg to train\Apple
Moved image_040.jpg to train\Xiaomi
Moved image_186.jpg to train\Samsung
Moved image_104.jpg to train\Nokia
Moved image_139.jpg to train\Samsung
Moved image_269.jpg to train\Samsung
Moved image_161.jpg to train\Samsung
Moved image_283.jpg to train\Nokia
Moved image_081.jpg to train\Xiaomi
Moved image_024.jpg to train\Samsung
Moved image_226.jpg to train\Samsung
Moved image_017.jpg to train\Samsung
Moved image_197.jpg to train\Samsung
Moved image_288.jpg to train\Xiaomi
Moved image_084.jpg to train\Samsung
Moved image_031.jpg to train\Motorola
Moved image_186.jpg to train\Samsung
Moved image_030.jpg to train\Samsung
Moved image_279.jpg to train\Apple
Moved image_006.jpg to train\Samsung
Moved image_155.jpg to train\Samsung
Moved image_003.jpg to train\Xiaomi
Moved image_121.jpg to train\Apple
Moved image_203.jpg to train\Xiaomi
Moved image_274.jpg to train\Apple
Moved image_301.jpg to train\Poco
Moved image_063.jpg to train\Xiaomi
Moved image_159.jpg to train\Samsung
Moved image_032.jpg to train\Motorola
Moved image_268.jpg to train\Samsung
Moved image_013.jpg to train\Xiaomi
Moved image_303.jpg to train\Xiaomi
Moved image_102.jpg to train\Samsung
Moved image_237.jpg to train\Samsung
Moved image_171.jpg to train\Samsung
Moved image_054.jpg to train\Samsung
Moved image_317.jpg to train\OnePlus
Moved image_054.jpg to train\Samsung
Moved image_262.jpg to train\Samsung
Moved image_251.jpg to train\Samsung
Moved image_218.jpg to train\Samsung
Moved image_149.jpg to train\Samsung
Moved image_195.jpg to train\Samsung
Moved image_005.jpg to train\Samsung
Moved image_056.jpg to train\Motorola
Moved image_322.jpg to train\OnePlus
Moved image_155.jpg to train\Samsung
Moved image_250.jpg to train\Samsung
Moved image_205.jpg to train\Samsung
Moved image_212.jpg to train\Motorola
Moved image_208.jpg to train\Samsung
Moved image_300.jpg to train\Xiaomi
Moved image_083.jpg to train\Xiaomi
Moved image_239.jpg to train\Samsung
Moved image_115.jpg to train\Samsung
Moved image_283.jpg to train\Nokia
Moved image_239.jpg to train\Samsung
Moved image_261.jpg to train\Samsung
Moved image_204.jpg to train\Samsung
Moved image_255.jpg to train\Samsung
Moved image_055.jpg to train\Samsung
Moved image_106.jpg to train\Samsung
Moved image_039.jpg to train\Samsung
Moved image_017.jpg to train\Samsung
Moved image_219.jpg to train\Samsung
Moved image_275.jpg to train\Apple
Moved image_227.jpg to train\Samsung
Moved image_093.jpg to train\Xiaomi
Moved image_020.jpg to train\Samsung
Moved image_247.jpg to train\Samsung
Moved image_232.jpg to train\Samsung
Moved image_038.jpg to train\Xiaomi
Moved image_322.jpg to train\OnePlus
Moved image_002.jpg to train\Motorola
Moved image_284.jpg to train\Nokia
Moved image_092.jpg to train\Redmi
Moved image_002.jpg to train\Motorola
Moved image_091.jpg to train\Xiaomi
Moved image_020.jpg to train\Samsung
Moved image_038.jpg to train\Xiaomi
Moved image_304.jpg to train\Poco
Moved image_011.jpg to train\Samsung
Moved image_080.jpg to train\Xiaomi
Moved image_131.jpg to train\Samsung
Moved image_064.jpg to train\Xiaomi
Moved image_218.jpg to train\Samsung
Moved image_110.jpg to train\Samsung
Moved image_314.jpg to train\OnePlus
Moved image_263.jpg to train\Samsung
Moved image_163.jpg to train\Motorola
Moved image_213.jpg to train\Nokia
Moved image_342.jpg to train\Nokia
Moved image_145.jpg to train\Xiaomi
Moved image_268.jpg to train\Samsung
Moved image_141.jpg to train\Samsung
Moved image_011.jpg to train\Samsung
Moved image_350.jpg to train\Nokia
Moved image_099.jpg to train\Samsung
Moved image_105.jpg to train\Samsung
Moved image_273.jpg to train\Apple
Moved image_322.jpg to train\OnePlus
Moved image_169.jpg to train\Samsung
Moved image_200.jpg to train\Xiaomi
Moved image_269.jpg to train\Samsung
Moved image_130.jpg to train\Samsung
Moved image_386.jpg to train\Apple
Moved image_360.jpg to train\Apple
Moved image_323.jpg to train\OnePlus
Moved image_302.jpg to train\Xiaomi
Moved image_364.jpg to train\Samsung
Moved image_013.jpg to train\Xiaomi
Moved image_080.jpg to train\Xiaomi
Moved image_311.jpg to train\Xiaomi
Moved image_386.jpg to train\Apple
Moved image_222.jpg to train\Samsung
Moved image_385.jpg to train\Apple
Moved image_140.jpg to train\Nokia
Moved image_095.jpg to train\Samsung
Moved image_126.jpg to train\Apple
Moved image_212.jpg to train\Motorola
Moved image_222.jpg to train\Samsung
Moved image_331.jpg to train\Nokia
Moved image_150.jpg to train\Samsung
Moved image_320.jpg to train\OnePlus
Moved image_109.jpg to train\Samsung
Moved image_245.jpg to train\Samsung
Moved image_325.jpg to train\OnePlus
Moved image_033.jpg to train\Samsung
Moved image_258.jpg to train\Xiaomi
Moved image_127.jpg to train\Apple
Moved image_361.jpg to train\Apple
Moved image_144.jpg to train\Samsung
Moved image_114.jpg to train\Samsung
Moved image_400.jpg to train\Nokia
Moved image_359.jpg to train\Apple
Moved image_099.jpg to train\Samsung
Moved image_007.jpg to train\Samsung
Moved image_011.jpg to train\Samsung
Moved image_320.jpg to train\OnePlus
Moved image_118.jpg to train\Samsung
Moved image_035.jpg to train\Samsung
Moved image_298.jpg to train\Xiaomi
Moved image_142.jpg to train\Samsung
Moved image_408.jpg to train\Redmi
Moved image_365.jpg to train\Apple
Moved image_274.jpg to train\Apple
Moved image_311.jpg to train\Xiaomi
Moved image_155.jpg to train\Samsung
Moved image_338.jpg to train\Samsung
Moved image_110.jpg to train\Samsung
Moved image_178.jpg to train\Samsung
Moved image_171.jpg to train\Samsung
Moved image_360.jpg to train\Apple
Moved image_332.jpg to train\Nokia
Moved image_270.jpg to train\Xiaomi
Moved image_183.jpg to train\Samsung
Moved image_098.jpg to train\Xiaomi
Moved image_290.jpg to train\Xiaomi
Moved image_406.jpg to train\Samsung
Moved image_397.jpg to train\Samsung
Moved image_407.jpg to train\Apple
Moved image_087.jpg to train\Xiaomi
Moved image_354.jpg to train\Nokia
Moved image_071.jpg to train\Xiaomi
Moved image_090.jpg to train\Xiaomi
Moved image_304.jpg to train\Poco
Moved image_387.jpg to train\Apple
Moved image_443.jpg to train\Nokia
Moved image_277.jpg to train\Apple
Moved image_141.jpg to train\Samsung
Moved image_267.jpg to train\Samsung
Moved image_387.jpg to train\Apple
Moved image_251.jpg to train\Samsung
Moved image_251.jpg to train\Samsung
Moved image_033.jpg to train\Samsung
Moved image_367.jpg to train\Samsung
Moved image_017.jpg to train\Samsung
Moved image_180.jpg to train\Samsung
Moved image_434.jpg to train\Nokia
Moved image_252.jpg to train\Nokia
Moved image_059.jpg to train\Samsung
Moved image_030.jpg to train\Samsung
Moved image_267.jpg to train\Samsung
Moved image_357.jpg to train\Samsung
Moved image_360.jpg to train\Apple
Moved image_304.jpg to train\Poco
Moved image_138.jpg to train\Samsung
Moved image_013.jpg to train\Xiaomi
Moved image_305.jpg to train\Poco
Moved image_258.jpg to train\Xiaomi
Moved image_424.jpg to train\Redmi
Moved image_409.jpg to train\Apple
Moved image_398.jpg to train\Samsung
Moved image_373.jpg to train\Apple
Moved image_431.jpg to train\Samsung
Moved image_257.jpg to train\Motorola
Moved image_279.jpg to train\Apple
Moved image_019.jpg to train\Samsung
Moved image_098.jpg to train\Xiaomi
Moved image_426.jpg to train\Samsung
Moved image_307.jpg to train\Xiaomi
Moved image_033.jpg to train\Samsung
Moved image_273.jpg to train\Apple
Moved image_017.jpg to train\Samsung
Moved image_237.jpg to train\Samsung
Moved image_034.jpg to train\Xiaomi
Moved image_263.jpg to train\Samsung
Moved image_071.jpg to train\Xiaomi
Moved image_238.jpg to train\Samsung
Moved image_162.jpg to train\Samsung
Moved image_069.jpg to train\Nokia
Moved image_145.jpg to train\Xiaomi
Moved image_353.jpg to train\Samsung
Moved image_131.jpg to train\Samsung
Moved image_208.jpg to train\Samsung
Moved image_220.jpg to train\Samsung
Moved image_148.jpg to train\Samsung
Moved image_016.jpg to train\Samsung
Moved image_331.jpg to train\Nokia
Moved image_247.jpg to train\Samsung
Moved image_129.jpg to train\Samsung
Moved image_044.jpg to train\Nokia
Moved image_174.jpg to train\Samsung
Moved image_487.jpg to train\Redmi
Moved image_131.jpg to train\Samsung
Moved image_059.jpg to train\Samsung
Moved image_384.jpg to train\Apple
Moved image_330.jpg to train\Samsung
Moved image_105.jpg to train\Samsung
Moved image_026.jpg to train\Xiaomi
Moved image_417.jpg to train\Apple
Moved image_314.jpg to train\OnePlus
Moved image_022.jpg to train\Samsung
Moved image_234.jpg to train\Samsung
Moved image_177.jpg to train\Samsung
Moved image_005.jpg to train\Samsung
Moved image_463.jpg to train\Samsung
Moved image_059.jpg to train\Samsung
Moved image_150.jpg to train\Samsung
Moved image_482.jpg to train\Samsung
Moved image_152.jpg to train\Samsung
Moved image_278.jpg to train\Apple
Moved image_476.jpg to train\Nokia
Moved image_288.jpg to train\Xiaomi
Moved image_053.jpg to train\Xiaomi
Moved image_523.jpg to train\Motorola
Moved image_221.jpg to train\Motorola
Moved image_295.jpg to train\Xiaomi
Moved image_319.jpg to train\OnePlus
Moved image_463.jpg to train\Samsung
Moved image_212.jpg to train\Motorola
Moved image_241.jpg to train\Samsung
Moved image_481.jpg to train\Redmi
Moved image_305.jpg to train\Poco
Moved image_509.jpg to train\Nokia
Moved image_304.jpg to train\Poco
Moved image_230.jpg to train\Samsung
Moved image_004.jpg to train\Samsung
Moved image_216.jpg to train\Samsung
Moved image_400.jpg to train\Nokia
Moved image_493.jpg to train\Samsung
Moved image_367.jpg to train\Samsung
Moved image_157.jpg to train\Samsung
Moved image_473.jpg to train\Xiaomi
Moved image_011.jpg to train\Samsung

Redistributing new images with updated train and test sizes:
+ Remove the remain exissting images with the old train and test sizes 
+ Update the train and test sizes
+ Redistribute the images with updated train and test sizes

## Reorganising images based on its label

+ finding number of images per training, testing and validation folders
+ finding number of images per class label folders

In [9]:
distributed_path = "D:\\Machine_Learning\\Portfolio_Project_Machine_Learning\\Mobile_Phone_Recognition\\datasets\\distributed_images"
distributed_path_list = os.listdir(distributed_path)

train_path = os.path.join(distributed_path, "train")
test_path = os.path.join(distributed_path, "test")
validation_pth = os.path.join(distributed_path, "validation")

print(f"Training folder: {train_path}")
print(f"Testing folder: {test_path}")
# print(f"Validation folder: {validation_path}")

Training folder: D:\Machine_Learning\Portfolio_Project_Machine_Learning\Mobile_Phone_Recognition\datasets\distributed_images\train
Testing folder: D:\Machine_Learning\Portfolio_Project_Machine_Learning\Mobile_Phone_Recognition\datasets\distributed_images\test

In [15]:
# define folder size: train, test, validation 
image_train_counter = det_folder_size(sel_path=train_path)
image_test_counter = det_folder_size(sel_path=test_path)
# image_val_counter = det_folder_size(sel_path=validation_pth)

# convert into dataframe
image_counter_df = pd.DataFrame()
image_counter_df["Image_Labels"] = image_train_counter.keys()
image_counter_df["Train_size"] = image_train_counter.values()
image_counter_df["Test_size"] = image_test_counter.values()
# image_counter_df["Validation_size"] = image_val_counter.values()

In [16]:
image_counter_df

  Image_Labels  Train_size  Test_size
0        Apple          24         26
1     Motorola          14          8
2        Nokia          26         27
3      OnePlus           7         11
4         Poco           3          3
5        Redmi           7          2
6      Samsung         144         86
7       Xiaomi          51         28

In [17]:
image_counter_df["Train_size"].sum()

np.int64(276)

In [18]:
image_total_set = pd.DataFrame()
image_total_set["Train_sum"] = pd.Series(image_counter_df["Train_size"].sum())
image_total_set["Test_sum"] = pd.Series(image_counter_df["Test_size"].sum())
# image_total_set["Valdation_sum"] = pd.Series(image_counter_df["Validation_size"].sum())

# image_total_set = image_total_set.transpose()
image_total_set.transpose()

             0
Train_sum  276
Test_sum   191