# Data Preparation

In [2]:
import cv2 as cv 
import numpy as np 
import pandas as pd 
import tensorflow as tf 
from tensorflow.keras.preprocessing import image

### Approach 

+ Reorganising images into datasets
+ Data Augmentation
+ Splitting data into training and testing sets

## Reorganisation Data

In [16]:
# load dataset
image_file = r"D:\Machine_Learning\Portfolio_Project_Machine_Learning\Mobile_Phone_Recognition\model_development\image_dataset.csv"
mobile_df = pd.read_csv(image_file, index_col=0)
mobile_df.head()

      Image_file  ...   Company
0  image_001.jpg  ...   Samsung
1  image_002.jpg  ...   Samsung
2  image_003.jpg  ...  Motorola
3  image_004.jpg  ...    Xiaomi
4  image_005.jpg  ...   Samsung

[5 rows x 4 columns]

In [ ]:
# extract mobile company data
mobile_classes = mobile_df["Company"].unique()
mobile_classes

array(['Samsung', 'Motorola', 'Xiaomi', 'SAMSUNG', 'Smartphone', 'XIAOMI',
       'Nokia', 'Redmi', 'Apple', 'NOKIA', 'POCO', 'Galaxy', 'Sam', 'ATI',
       'Moto', 'Telecom', 'XIA', 'APPLE', 'iPhone', 'Poco', 'OnePlus',
       'Oneplus', 'Free', 'apple', 'Unlocked', 'SMARTPHONE', 'M4',
       'GenÃ©rico'], dtype=object)

In [20]:
mobile_df["Company"].value_counts().head()

Company
Samsung    285
Xiaomi     153
Nokia       99
Apple       89
SAMSUNG     46
Name: count, dtype: int64

In [ ]:
mobile_df[mobile_df["Company"].str.contains("Unlocked")]
mobile_df[]

        Image_file  ...   Company
440  image_441.jpg  ...  Unlocked

[1 rows x 4 columns]